#import "../../modules/blog/components/PostListItem/fragment.gql"

query BLOG($limit: Int!, $start: Int!) {
  posts(limit: $limit, start: $start) {
    id
    items {
      id
      item {
        id
        ...PostListItem
      }
    }
  }
}
