version: "2"
services:
  db:
    image: mysql
    container_name: slpg--next-srapi--db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - $PWD/.db:/var/lib/mysql
    ports:
      - 3307:3307
    # security_opt:
    #   - seccomp:unconfined
    env_file:
      - .env
