version: "2"
services:
  db:
    image: mysql
    container_name: slpg--next-srapi--db
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - $PWD/.db:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env
