#import "../modules/blog/components/PostListItem/fragment.gql"

query BLOG_LATEST {
  posts(limit: 3) {
    id
    items {
      id
      item {
        id
        ...PostListItem
      }
    }
  }
}
