import styled from 'styled-components'
import classnames from 'classnames'

export const a = <Props extends {}>(classNames: TemplateStringsArray) => styled.a.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const abbr = <Props extends {}>(classNames: TemplateStringsArray) => styled.abbr.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const address = <Props extends {}>(classNames: TemplateStringsArray) => styled.address.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const area = <Props extends {}>(classNames: TemplateStringsArray) => styled.area.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const article = <Props extends {}>(classNames: TemplateStringsArray) => styled.article.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const aside = <Props extends {}>(classNames: TemplateStringsArray) => styled.aside.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const audio = <Props extends {}>(classNames: TemplateStringsArray) => styled.audio.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const b = <Props extends {}>(classNames: TemplateStringsArray) => styled.b.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const base = <Props extends {}>(classNames: TemplateStringsArray) => styled.base.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const bdi = <Props extends {}>(classNames: TemplateStringsArray) => styled.bdi.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const bdo = <Props extends {}>(classNames: TemplateStringsArray) => styled.bdo.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const big = <Props extends {}>(classNames: TemplateStringsArray) => styled.big.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const blockquote = <Props extends {}>(classNames: TemplateStringsArray) => styled.blockquote.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const body = <Props extends {}>(classNames: TemplateStringsArray) => styled.body.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const br = <Props extends {}>(classNames: TemplateStringsArray) => styled.br.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const button = <Props extends {}>(classNames: TemplateStringsArray) => styled.button.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const canvas = <Props extends {}>(classNames: TemplateStringsArray) => styled.canvas.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const caption = <Props extends {}>(classNames: TemplateStringsArray) => styled.caption.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const cite = <Props extends {}>(classNames: TemplateStringsArray) => styled.cite.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const code = <Props extends {}>(classNames: TemplateStringsArray) => styled.code.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const col = <Props extends {}>(classNames: TemplateStringsArray) => styled.col.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const colgroup = <Props extends {}>(classNames: TemplateStringsArray) => styled.colgroup.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const data = <Props extends {}>(classNames: TemplateStringsArray) => styled.data.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const datalist = <Props extends {}>(classNames: TemplateStringsArray) => styled.datalist.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const dd = <Props extends {}>(classNames: TemplateStringsArray) => styled.dd.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const del = <Props extends {}>(classNames: TemplateStringsArray) => styled.del.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const details = <Props extends {}>(classNames: TemplateStringsArray) => styled.details.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const dfn = <Props extends {}>(classNames: TemplateStringsArray) => styled.dfn.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const dialog = <Props extends {}>(classNames: TemplateStringsArray) => styled.dialog.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const div = <Props extends {}>(classNames: TemplateStringsArray) => styled.div.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const dl = <Props extends {}>(classNames: TemplateStringsArray) => styled.dl.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const dt = <Props extends {}>(classNames: TemplateStringsArray) => styled.dt.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const em = <Props extends {}>(classNames: TemplateStringsArray) => styled.em.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const embed = <Props extends {}>(classNames: TemplateStringsArray) => styled.embed.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const fieldset = <Props extends {}>(classNames: TemplateStringsArray) => styled.fieldset.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const figcaption = <Props extends {}>(classNames: TemplateStringsArray) => styled.figcaption.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const figure = <Props extends {}>(classNames: TemplateStringsArray) => styled.figure.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const footer = <Props extends {}>(classNames: TemplateStringsArray) => styled.footer.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const form = <Props extends {}>(classNames: TemplateStringsArray) => styled.form.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const h1 = <Props extends {}>(classNames: TemplateStringsArray) => styled.h1.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const h2 = <Props extends {}>(classNames: TemplateStringsArray) => styled.h2.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const h3 = <Props extends {}>(classNames: TemplateStringsArray) => styled.h3.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const h4 = <Props extends {}>(classNames: TemplateStringsArray) => styled.h4.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const h5 = <Props extends {}>(classNames: TemplateStringsArray) => styled.h5.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const h6 = <Props extends {}>(classNames: TemplateStringsArray) => styled.h6.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const head = <Props extends {}>(classNames: TemplateStringsArray) => styled.head.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const header = <Props extends {}>(classNames: TemplateStringsArray) => styled.header.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const hgroup = <Props extends {}>(classNames: TemplateStringsArray) => styled.hgroup.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const hr = <Props extends {}>(classNames: TemplateStringsArray) => styled.hr.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const html = <Props extends {}>(classNames: TemplateStringsArray) => styled.html.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const i = <Props extends {}>(classNames: TemplateStringsArray) => styled.i.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const iframe = <Props extends {}>(classNames: TemplateStringsArray) => styled.iframe.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const img = <Props extends {}>(classNames: TemplateStringsArray) => styled.img.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const input = <Props extends {}>(classNames: TemplateStringsArray) => styled.input.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const ins = <Props extends {}>(classNames: TemplateStringsArray) => styled.ins.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const kbd = <Props extends {}>(classNames: TemplateStringsArray) => styled.kbd.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const keygen = <Props extends {}>(classNames: TemplateStringsArray) => styled.keygen.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const label = <Props extends {}>(classNames: TemplateStringsArray) => styled.label.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const legend = <Props extends {}>(classNames: TemplateStringsArray) => styled.legend.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const li = <Props extends {}>(classNames: TemplateStringsArray) => styled.li.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const link = <Props extends {}>(classNames: TemplateStringsArray) => styled.link.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const main = <Props extends {}>(classNames: TemplateStringsArray) => styled.main.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const map = <Props extends {}>(classNames: TemplateStringsArray) => styled.map.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const mark = <Props extends {}>(classNames: TemplateStringsArray) => styled.mark.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
// export const marquee = <Props extends {}>(classNames: TemplateStringsArray) => styled.marquee.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const menu = <Props extends {}>(classNames: TemplateStringsArray) => styled.menu.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const menuitem = <Props extends {}>(classNames: TemplateStringsArray) => styled.menuitem.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const meta = <Props extends {}>(classNames: TemplateStringsArray) => styled.meta.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const meter = <Props extends {}>(classNames: TemplateStringsArray) => styled.meter.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const nav = <Props extends {}>(classNames: TemplateStringsArray) => styled.nav.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const noscript = <Props extends {}>(classNames: TemplateStringsArray) => styled.noscript.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const object = <Props extends {}>(classNames: TemplateStringsArray) => styled.object.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const ol = <Props extends {}>(classNames: TemplateStringsArray) => styled.ol.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const optgroup = <Props extends {}>(classNames: TemplateStringsArray) => styled.optgroup.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const option = <Props extends {}>(classNames: TemplateStringsArray) => styled.option.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const output = <Props extends {}>(classNames: TemplateStringsArray) => styled.output.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const p = <Props extends {}>(classNames: TemplateStringsArray) => styled.p.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const param = <Props extends {}>(classNames: TemplateStringsArray) => styled.param.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const picture = <Props extends {}>(classNames: TemplateStringsArray) => styled.picture.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const pre = <Props extends {}>(classNames: TemplateStringsArray) => styled.pre.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const progress = <Props extends {}>(classNames: TemplateStringsArray) => styled.progress.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const q = <Props extends {}>(classNames: TemplateStringsArray) => styled.q.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const rp = <Props extends {}>(classNames: TemplateStringsArray) => styled.rp.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const rt = <Props extends {}>(classNames: TemplateStringsArray) => styled.rt.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const ruby = <Props extends {}>(classNames: TemplateStringsArray) => styled.ruby.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const s = <Props extends {}>(classNames: TemplateStringsArray) => styled.s.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const samp = <Props extends {}>(classNames: TemplateStringsArray) => styled.samp.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const script = <Props extends {}>(classNames: TemplateStringsArray) => styled.script.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const section = <Props extends {}>(classNames: TemplateStringsArray) => styled.section.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const select = <Props extends {}>(classNames: TemplateStringsArray) => styled.select.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const small = <Props extends {}>(classNames: TemplateStringsArray) => styled.small.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const source = <Props extends {}>(classNames: TemplateStringsArray) => styled.source.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const span = <Props extends {}>(classNames: TemplateStringsArray) => styled.span.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const strong = <Props extends {}>(classNames: TemplateStringsArray) => styled.strong.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const style = <Props extends {}>(classNames: TemplateStringsArray) => styled.style.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const sub = <Props extends {}>(classNames: TemplateStringsArray) => styled.sub.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const summary = <Props extends {}>(classNames: TemplateStringsArray) => styled.summary.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const sup = <Props extends {}>(classNames: TemplateStringsArray) => styled.sup.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const table = <Props extends {}>(classNames: TemplateStringsArray) => styled.table.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const tbody = <Props extends {}>(classNames: TemplateStringsArray) => styled.tbody.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const td = <Props extends {}>(classNames: TemplateStringsArray) => styled.td.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const textarea = <Props extends {}>(classNames: TemplateStringsArray) => styled.textarea.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const tfoot = <Props extends {}>(classNames: TemplateStringsArray) => styled.tfoot.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const th = <Props extends {}>(classNames: TemplateStringsArray) => styled.th.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const thead = <Props extends {}>(classNames: TemplateStringsArray) => styled.thead.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const time = <Props extends {}>(classNames: TemplateStringsArray) => styled.time.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const title = <Props extends {}>(classNames: TemplateStringsArray) => styled.title.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const tr = <Props extends {}>(classNames: TemplateStringsArray) => styled.tr.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const track = <Props extends {}>(classNames: TemplateStringsArray) => styled.track.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const u = <Props extends {}>(classNames: TemplateStringsArray) => styled.u.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const ul = <Props extends {}>(classNames: TemplateStringsArray) => styled.ul.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
// export const var = <Props extends {}>(classNames: TemplateStringsArray) => styled.var.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const video = <Props extends {}>(classNames: TemplateStringsArray) => styled.video.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const wbr = <Props extends {}>(classNames: TemplateStringsArray) => styled.wbr.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const circle = <Props extends {}>(classNames: TemplateStringsArray) => styled.circle.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const clipPath = <Props extends {}>(classNames: TemplateStringsArray) => styled.clipPath.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const defs = <Props extends {}>(classNames: TemplateStringsArray) => styled.defs.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const ellipse = <Props extends {}>(classNames: TemplateStringsArray) => styled.ellipse.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const foreignObject = <Props extends {}>(classNames: TemplateStringsArray) => styled.foreignObject.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const g = <Props extends {}>(classNames: TemplateStringsArray) => styled.g.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const image = <Props extends {}>(classNames: TemplateStringsArray) => styled.image.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const line = <Props extends {}>(classNames: TemplateStringsArray) => styled.line.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const linearGradient = <Props extends {}>(classNames: TemplateStringsArray) => styled.linearGradient.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const marker = <Props extends {}>(classNames: TemplateStringsArray) => styled.marker.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const mask = <Props extends {}>(classNames: TemplateStringsArray) => styled.mask.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const path = <Props extends {}>(classNames: TemplateStringsArray) => styled.path.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const pattern = <Props extends {}>(classNames: TemplateStringsArray) => styled.pattern.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const polygon = <Props extends {}>(classNames: TemplateStringsArray) => styled.polygon.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const polyline = <Props extends {}>(classNames: TemplateStringsArray) => styled.polyline.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const radialGradient = <Props extends {}>(classNames: TemplateStringsArray) => styled.radialGradient.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const rect = <Props extends {}>(classNames: TemplateStringsArray) => styled.rect.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const stop = <Props extends {}>(classNames: TemplateStringsArray) => styled.stop.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const svg = <Props extends {}>(classNames: TemplateStringsArray) => styled.svg.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const text = <Props extends {}>(classNames: TemplateStringsArray) => styled.text.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``
export const tspan = <Props extends {}>(classNames: TemplateStringsArray) => styled.tspan.attrs<Props>(({ className }) => ({ className: classnames(className, classNames).join(' ') }))<Props>``