backend:
  name: github
  repo: lucasconstantino/slpg
  branch: netlify
media_folder: src/admin/content/media
public_folder: /admin/content/media
publish_mode: editorial_workflow
collections:
  - name: 'blog'
    label: 'Blogue'
    folder: src/admin/content/blog
    create: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Data de Publicação', name: 'date', widget: 'datetime' }
      - {
          label: 'Imagem de Destaque',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - { label: 'Corpo', name: 'body', widget: 'markdown' }
      - { label: 'Chamada', name: 'summary', widget: 'text' }

  - name: 'team'
    label: 'Equipe'
    folder: src/admin/content/team
    create: true
    identifier_field: name
    format: json
    fields:
      - { label: 'Nome', name: 'name', widget: 'string' }
      - { label: 'Cargo', name: 'role', widget: 'string' }
      - { label: 'OAB', name: 'oab', widget: 'string' }
      - { label: 'Foto', name: 'photo', widget: 'image' }

  - label: 'Configurações'
    name: 'misc'
    files:
      - label: 'Equipe'
        name: 'team'
        file: 'src/admin/content/team.yml'
        fields:
          - label: 'Membros'
            name: 'members'
            widget: 'list'
            fields:
              - {
                  label: 'Referência',
                  name: 'reference',
                  widget: 'relation',
                  collection: 'team',
                  searchFields: ['name'],
                  valueField: 'name',
                  displayFields: ['name'],
                }
