const env = {
  NODE_ENV: process.env.NODE_ENV,

  MAILCHIMP_AUDIENCE: process.env.MAILCHIMP_AUDIENCE,
  // prettier-ignore
  MAILCHIMP_INTERESTS_CATEGORY: process.env.MAILCHIMP_INTERESTS_CATEGORY,
  MAILCHIMP_API_KEY: process.env.MAILCHIMP_API_KEY,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_REFRESH_TOKEN: process.env.GOOGLE_REFRESH_TOKEN,
  GOOGLE_TO_EMAIL: process.env.GOOGLE_TO_EMAIL,
  GOOGLE_USER: process.env.GOOGLE_USER,
  TYPE_FORM_TOKEN: process.env.TYPE_FORM_TOKEN,
  AIRTABLE_API_KEY: process.env.AIRTABLE_API_KEY,
}

export { env }
